services:
  - type: web
    name: tailortalk-calendar
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: OPENAI_API_KEY
        fromEnvVar: OPENAI_API_KEY
      - key: OPENAI_MODEL_NAME
        fromEnvVar: OPENAI_MODEL_NAME
      - key: OPENAI_API_BASE
        fromEnvVar: OPENAI_API_BASE
    secretFiles:
      - source: calendar-service-account.json
        target: /etc/secrets/calendar-service-account.json
